; PlatformIO Project Configuration File

[platformio]
default_envs = smini-esp32c3

[env]
platform = espressif32
framework = arduino
board_build.flash_mode = qio
upload_port = /dev/ttyACM*
monitor_port = /dev/ttyACM*
monitor_speed = 115200

[env:smini-esp32c3]
board = esp32-c3-devkitm-1
board_build.partitions = partitions4M.csv
upload_speed = 460800
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I include
    -I src
    -I lib
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    electroniccats/MPU6050@^1.4.1
    pololu/VL6180X @ ^1.4.0
